# Define the "upstream" servers (the names match your service names in docker-compose)
upstream backend_api {
    server backend:8000;
}

server {
    listen 80;

    # 1. Routing for Django API
    location /api/ {
        proxy_pass http://backend_api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # 2. Routing for Django Admin (very useful)
    location /admin/ {
        proxy_pass http://backend_api;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # 3. Routing for React Frontend
    # location / {
    #     # This matches the "frontend" service and port in your docker-compose
    #     proxy_pass http://frontend:3000;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header Host $host;
    #     proxy_redirect off;
    #     
    #     # Enable WebSockets for React Hot Module Replacement (Dev mode)
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    # }

    # 3. React Frontend (ARTIK PROXY DEĞİL, DOĞRUDAN DOSYA SUNUMU)
    location / {
        root /usr/share/nginx/html; 
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 4. Static files shared via volumes
    location /static/ {
        alias /app/staticfiles/;
    }
}